### PR TITLE
Update podspecs for v1.0.0-rc1

### PR DESCRIPTION
**Pull request by rebello95**

### CODE REVIEW

**Review by jhump — APPROVED** [review]
Ship it!

Aside: we should probably address all of the annotations on unchanged files before the next release candidate.

**Comment by rebello95** [comment]
> Aside: we should probably address all of the annotations on unchanged files before the next release candidate.

Sorry, @jhump not quite sure what you're referring to - can you clarify?

**Comment by jhump** [comment]
When I look at the file view of this PR (and other recent PRs), I see a bunch of things like this:
image

**Comment by rebello95** [comment]
Thanks for flagging @jhump. I merged `main` into this PR because https://github.com/connectrpc/connect-swift/pull/284 should have fixed those issues, and indeed they've disappeared from the file viewer now

**Pull request merged**
