### PR TITLE
Allow additional path extensions on configured hosts

### PR DESCRIPTION
**Pull request by rebello95**
This adds support for specifying hosts with additional path extensions, such as `https://connectrpc.com/a/b/c/`. Previously, `/a/b/c` would be dropped.

Resolves https://github.com/connectrpc/connect-swift/issues/252.

Also related to https://github.com/connectrpc/connect-swift/issues/161.

### CODE REVIEW

**Review by oliverfoggin — APPROVED** [review]
Great!

Thanks for making these changes so quickly!

**Review by oliverfoggin — CHANGES_REQUESTED** [review]
Looking at this it appears to add an additional `/` if one already exists.

In this code... 

```
let url = URL(string: "https://foo.com/x/y/z/")!.appendingPathComponent("/a/b/c")
```

The resulting URL is...

```
https://foo.com/x/y/z//a/b/c
```

image

Thanks

**Comment by oliverfoggin** [comment]
It looks like `appendingPathComponent("path")` is deprecated in favour of `appending(path: "path")` but this still has the same issue of the doubled `//`. 😅

image

**Comment by rebello95** [comment]
Thanks for taking a look @oliverfoggin. I'm not seeing the issue you're describing, and I had added a test case for hosts with trailing `/` components which passed (I also just updated the tests to explicitly use the `/a/b/c` examples).

Running locally, this is also what I get:
```
print(ProtocolClientConfig(host: "https://connectrpc.com/a/b/c/")
    .createURL(forPath: rpcPath))

> https://connectrpc.com/a/b/c/connectrpc.conformance.v1.ConformanceService/Unary
```
Which is correct, so I'm not sure why the playground is showing something different.

Can you try checking out this branch as your Connect dependency and seeing if it solves your problem?

> It looks like appendingPathComponent("path") is deprecated in favour of appending(path: "path")

It doesn't look like it's been fully deprecated, but seems like there is a newly preferred version:

Screenshot 2024-03-28 at 6 09 09 AM

However, the new version is not available in the target SDK for Connect, and I think it'd be safer to have one implementation rather than `if #available()` and having 2 codepaths since we aren't getting compilation warnings:

Screenshot 2024-03-28 at 6 09 45 AM

**Review by oliverfoggin — APPROVED** [review]

**Comment by rebello95** [comment]
CI failures are unrelated, working with @jhump to resolve

**Review by akshayjshah — APPROVED** [review]

**Comment by oliverfoggin** [comment]
I'm on Xcode 15.3 and Sonoma 14.4

Thanks for the update with this. Will check it out and continue on with the project. 😄

**Comment by oliverfoggin** [comment]
@rebello95 

Would it be possible to put a release out for this change? I'm pointing at `main` at the moment to get the change.

Thanks

**Comment by rebello95** [comment]
@oliverfoggin yea I think we can create a release once https://github.com/connectrpc/connect-swift/pull/247 merges

**Comment by oliverfoggin** [comment]
Great! Thanks 😃

**Pull request merged**
